version: '3.7'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: suggester-data
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
